/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._web_22dinf._pages._offline;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import com.lpmas.framework.config.*;
import com.lpmas.framework.bean.*;
import com.lpmas.framework.page.*;
import com.lpmas.framework.util.*;
import com.lpmas.framework.web.*;
import com.lpmas.system.bean.*;
import com.lpmas.system.client.cache.*;
import com.lpmas.admin.bean.*;
import com.lpmas.admin.business.*;
import com.lpmas.admin.config.*;
import com.lpmas.tpp.console.channel.offline.config.*;
import com.lpmas.tpp.console.channel.offline.bean.*;
import com.lpmas.framework.tools.common.bean.ImportResultBean;

public class _offlineorderinfoimport__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
	List<StoreInfoBean> storeList = (List<StoreInfoBean>)request.getAttribute("StoreList");
	int storeId = request.getAttribute("StoreId") !=null ? (Integer)request.getAttribute("StoreId") : 0;
	String tradeSource = request.getAttribute("TradeSource") !=null ? (String)request.getAttribute("TradeSource") : "";
	ImportResultBean importResultBean = (ImportResultBean)request.getAttribute("ImportResult");

    out.write(_jsp_string1, 0, _jsp_string1.length);
    String STATIC_URL = "http://test.portal.lpmas-admin.net:9010"; 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    String REGION_URL = "http://test.region.lpmas-admin.net:9030"; 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    String SYSTEM_URL = "http://test.system.lpmas-admin.net:9020"; 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    String DOMAIN = "lpmas-admin.net"; 
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((DOMAIN));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    
    	for(StoreInfoBean storeInfoBean:storeList){ 
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((storeInfoBean.getStoreId() ));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((storeId == storeInfoBean.getStoreId() ? "selected" : "" ));
    out.write('>');
    out.print((storeInfoBean.getStoreName() ));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    } 
    out.write(_jsp_string11, 0, _jsp_string11.length);
    if(importResultBean !=null){ 
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((importResultBean.getSuccessMsgList().get(0) ));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    if(!importResultBean.getErrorMsgList().isEmpty()) {
    out.write(_jsp_string14, 0, _jsp_string14.length);
    for(String msg : importResultBean.getErrorMsgList()) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((msg));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    }
    out.write(_jsp_string17, 0, _jsp_string17.length);
    }
    out.write(_jsp_string18, 0, _jsp_string18.length);
    } 
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((SYSTEM_URL));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((tradeSource));
    out.write(_jsp_string21, 0, _jsp_string21.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/offline/OfflineOrderInfoImport.jsp"), -5700300619743044485L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/include/header.jsp"), 3311372421660353148L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string19;
  private final static char []_jsp_string3;
  private final static char []_jsp_string14;
  private final static char []_jsp_string13;
  private final static char []_jsp_string16;
  private final static char []_jsp_string15;
  private final static char []_jsp_string4;
  private final static char []_jsp_string10;
  private final static char []_jsp_string0;
  private final static char []_jsp_string8;
  private final static char []_jsp_string1;
  private final static char []_jsp_string17;
  private final static char []_jsp_string11;
  private final static char []_jsp_string12;
  private final static char []_jsp_string21;
  private final static char []_jsp_string18;
  private final static char []_jsp_string6;
  private final static char []_jsp_string20;
  private final static char []_jsp_string2;
  private final static char []_jsp_string5;
  static {
    _jsp_string7 = "'; \r\n</script>\r\n</head>\r\n<body class=\"article_bg\">\r\n	<div class=\"article_tit\">\r\n		<ul class=\"art_nav\">\r\n			<li><a href=\"OfflineOrderInfoList.do\">\u7ebf\u4e0b\u8ba2\u5355\u5217\u8868</a>&nbsp;>&nbsp;\u5bfc\u5165\u8ba2\u5355</li>\r\n		</ul>\r\n	</div>\r\n	<form method=\"post\" id=\"formData\"  enctype=\"multipart/form-data\" action=\"\"  onsubmit=\"javascript:return formOnSubmit();\">		   \r\n		<div class=\"modify_form\">\r\n	   <p><em class=\"int_label\">\u5546\u5e97\uff1a</em>\r\n  	    <select name=\"storeId\" id=\"storeId\" onchange=\"$('#tradeSource').empty();getTradeSourceList('storeId','tradeSource','')\">\r\n  	   <option value=\"\"></option>\r\n    	".toCharArray();
    _jsp_string9 = "\" ".toCharArray();
    _jsp_string19 = "\r\n		</div>\r\n		<div class=\"div_center\">\r\n			<p>\r\n				\r\n				<input type=\"submit\" name=\"button\" id=\"button\" class=\"modifysubbtn\" value=\"\u63d0\u4ea4\" />\r\n				\r\n			</p>\r\n		</div>\r\n	</form>\r\n</body>\r\n<script>\r\nfunction formOnSubmit(){\r\n	var storeId = $(\"#storeId\").val();\r\n	var tradeSource = $(\"#tradeSource\").val(); \r\n	$(\"#formData\").attr(\"action\", \"OfflineOrderInfoImport.do?storeId=\"+storeId+\"&tradeSource=\"+tradeSource);\r\n	$(\"#formData\").submit();\r\n	return true;\r\n}	\r\n$(document).ready(function() {\r\n	//\u83b7\u53d6\u6765\u6e90\r\n		var url='".toCharArray();
    _jsp_string3 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n<title>\u7ebf\u4e0b\u8ba2\u5355\u5bfc\u5165</title>\r\n<link href=\"".toCharArray();
    _jsp_string14 = "\r\n				<div class=\"article_subtit\">\u9519\u8bef\u4fe1\u606f</div>\r\n				<div class=\"modify_form\">\r\n				  ".toCharArray();
    _jsp_string13 = "\r\n					</p>\r\n				</div>\r\n				".toCharArray();
    _jsp_string16 = "</p>\r\n					".toCharArray();
    _jsp_string15 = "\r\n						<p>".toCharArray();
    _jsp_string4 = "/css/main.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n<script type='text/javascript' src=\"".toCharArray();
    _jsp_string10 = "</option>\r\n        ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string8 = "\r\n        <option value=\"".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string17 = " \r\n				</div>\r\n				".toCharArray();
    _jsp_string11 = "\r\n        </select>\r\n        </p>\r\n        <p>\r\n        <em class=\"int_label\">\u6765\u6e90\uff1a</em>\r\n	  	<select name=\"tradeSource\" id=\"tradeSource\">\r\n	    </select>\r\n	    </p>\r\n			<p>\r\n				<em class=\"int_label\">\u5bfc\u5165\u7ebf\u4e0b\u8ba2\u5355\uff1a</em>\r\n				<input type=\"file\" name=\"file\" id=\"file\" size=\"80\" checkStr=\"\u6587\u4ef6;txt;true;;2000\" /><a href=\"/examples/OfflineOrderInfoSample.xls\" target=\"_blank\">\u6a21\u677f</a>\r\n			</p>\r\n			".toCharArray();
    _jsp_string12 = "\r\n				<div class=\"article_subtit\">\u5904\u7406\u7ed3\u679c</div>\r\n				<div class=\"modify_form\">\r\n					<p>\r\n						".toCharArray();
    _jsp_string21 = "');\r\n		});\r\n});\r\n</script>\r\n</html>".toCharArray();
    _jsp_string18 = "\r\n			 ".toCharArray();
    _jsp_string6 = "/js/common.js\"></script>\r\n<script type=\"text/javascript\">\r\n        document.domain='".toCharArray();
    _jsp_string20 = "/system/SystemAjaxList.do';\r\n		$.getScript(url,function(data){\r\n			getTradeSourceList('storeId','tradeSource','".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string5 = "/js/jquery.js\"></script>\r\n<script type='text/javascript' src=\"".toCharArray();
  }
}
