/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._web_22dinf._pages._offline;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.lpmas.framework.web.ParamKit;
import com.lpmas.framework.util.*;
import java.util.*;
import com.lpmas.framework.config.*;
import com.lpmas.framework.bean.StatusBean;
import com.lpmas.admin.bean.*;
import com.lpmas.admin.business.*;
import com.lpmas.oms.order.config.SalesOrderStatusConfig;
import com.lpmas.tpp.console.channel.offline.config.*;
import com.lpmas.tpp.console.channel.offline.bean.*;

public class _offlineorderinfomanage__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
     
    OfflineOrderInfoBean bean = (OfflineOrderInfoBean)request.getAttribute("OfflineOrder");
    List<OfflineOrderItemBean> itemBeanList = (List<OfflineOrderItemBean>)request.getAttribute("ItemBeanList");
	String expressCompanyName = (String)request.getAttribute("ExpressCompanyName");
	AdminUserHelper adminUserHelper = (AdminUserHelper)request.getAttribute("AdminUserHelper");
	HashMap<Integer,String> expressCompanyNameMap = (HashMap<Integer,String>)request.getAttribute("ExpressCompanyNameMap");

    out.write(_jsp_string1, 0, _jsp_string1.length);
    String STATIC_URL = "http://test.portal.lpmas-admin.net:9010"; 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    String REGION_URL = "http://test.region.lpmas-admin.net:9030"; 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    String SYSTEM_URL = "http://test.system.lpmas-admin.net:9020"; 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    String DOMAIN = "lpmas-admin.net"; 
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((bean.getOrderId()));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((bean.getOrderId() ));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((bean.getProvince()));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((bean.getCity()));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((bean.getRegion()));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((bean.getAddress()));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((bean.getReceiverName()));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((bean.getMobile()));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((expressCompanyName));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((bean.getExpressNumber()));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((bean.getTotalQuantity()));
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((bean.getOrderFactAmount()));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((SalesOrderStatusConfig.ORDER_STATUS_MAP.get(bean.getOrderStatus())));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    for(OfflineOrderItemBean itemBean : itemBeanList){ 
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((itemBean.getOrderItemId() ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((itemBean.getProductItemNumber() ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((itemBean.getQuantity() ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((itemBean.getFactPrice() ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((itemBean.getItemFactAmount() ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((MapKit.getValueFromMap(itemBean.getOrderItemId(), expressCompanyNameMap)));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((itemBean.getExpressNumber() ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    } 
    out.write(_jsp_string24, 0, _jsp_string24.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/offline/OfflineOrderInfoManage.jsp"), -1150056027772792954L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/include/header.jsp"), 3311372421660353148L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string9;
  private final static char []_jsp_string14;
  private final static char []_jsp_string22;
  private final static char []_jsp_string8;
  private final static char []_jsp_string3;
  private final static char []_jsp_string11;
  private final static char []_jsp_string6;
  private final static char []_jsp_string7;
  private final static char []_jsp_string20;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string23;
  private final static char []_jsp_string15;
  private final static char []_jsp_string18;
  private final static char []_jsp_string4;
  private final static char []_jsp_string19;
  private final static char []_jsp_string17;
  private final static char []_jsp_string10;
  private final static char []_jsp_string2;
  private final static char []_jsp_string12;
  private final static char []_jsp_string16;
  private final static char []_jsp_string21;
  private final static char []_jsp_string24;
  private final static char []_jsp_string5;
  private final static char []_jsp_string13;
  static {
    _jsp_string9 = "</em>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\">\u7701:</em>\r\n	       <em>".toCharArray();
    _jsp_string14 = "</em>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\">\u8054\u7cfb\u7535\u8bdd:</em>\r\n	       <em>".toCharArray();
    _jsp_string22 = "</td>\r\n      <td>".toCharArray();
    _jsp_string8 = "\r\n		</ul>\r\n	</div>\r\n	  <div class=\"modify_form\">\r\n	    <p>\r\n	      <em class=\"int_label\">\u8ba2\u5355ID:</em>\r\n	      <em>".toCharArray();
    _jsp_string3 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n	<title>\u8ba2\u5355\u8be6\u60c5</title>\r\n	<link href=\"".toCharArray();
    _jsp_string11 = "</em>\r\n	    </p>\r\n	     <p>\r\n	      <em class=\"int_label\">\u533a:</em>\r\n	       <em>".toCharArray();
    _jsp_string6 = "/js/common.js\"></script>\r\n</head>\r\n<body class=\"article_bg\">\r\n	<div class=\"article_tit\">\r\n		<a href=\"javascript:history.back()\" ><img src=\"".toCharArray();
    _jsp_string7 = "/images/back_forward.jpg\"/></a> \r\n		<ul class=\"art_nav\">\r\n			<li><a href=\"OfflineOrderInfoList.do\">\u8ba2\u5355\u5217\u8868</a>&nbsp;>&nbsp;</li>\r\n			".toCharArray();
    _jsp_string20 = "</em>\r\n	    </p>	    	    \r\n	  </div>\r\n	    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"table_style\">\r\n    <tr>\r\n      <th><input type=\"checkbox\" name=\"selectAllSoId\" id=\"selectAllSoId\" onclick=\"javascript:changeChiefCheckbox('selectAllSoId','selectSoId');\"/></th>\r\n      <th>\u660e\u7ec6ID</th>\r\n      <th>\u5546\u54c1\u9879\u7f16\u7801</th>      \r\n      <th>\u6570\u91cf</th>\r\n      <th>\u5b9e\u9645\u5355\u4ef7</th>\r\n      <th>\u5355\u9879\u603b\u4ef7</th>\r\n      <th>\u7269\u6d41\u516c\u53f8</th>\r\n      <th>\u7269\u6d41\u7f16\u53f7</th>\r\n    </tr>\r\n    ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string23 = "</td>\r\n    </tr>\r\n    ".toCharArray();
    _jsp_string15 = "</em>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\">\u7269\u6d41\u516c\u53f8:</em>\r\n	       <em>".toCharArray();
    _jsp_string18 = "</em>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\">\u8ba2\u5355\u5b9e\u9645\u603b\u989d:</em>\r\n	       <em>".toCharArray();
    _jsp_string4 = "/css/main.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string19 = "</em>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\">\u8ba2\u5355\u72b6\u6001:</em>\r\n	       <em>".toCharArray();
    _jsp_string17 = "</em>\r\n	    </p>\r\n	    <p>\r\n	    	  <em class=\"int_label\">\u6570\u91cf:</em>\r\n	      <em>".toCharArray();
    _jsp_string10 = "</em>\r\n	    </p>\r\n	     <p>\r\n	      <em class=\"int_label\">\u5e02:</em>\r\n	       <em>".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string12 = "</em>\r\n	    </p>\r\n	     <p>\r\n	      <em class=\"int_label\">\u5730\u5740:</em>\r\n	       <em>".toCharArray();
    _jsp_string16 = "</em>\r\n	    </p>\r\n	    <p>\r\n	       <em class=\"int_label\">\u7269\u6d41\u7f16\u53f7:</em>\r\n	       <em>".toCharArray();
    _jsp_string21 = "\r\n    <tr>\r\n      <td>&nbsp;</td>\r\n      <td>".toCharArray();
    _jsp_string24 = "   \r\n  </table>\r\n\r\n</body>\r\n</html>".toCharArray();
    _jsp_string5 = "/js/jquery.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string13 = "</em>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\">\u6536\u8d27\u4eba:</em>\r\n	       <em>".toCharArray();
  }
}
